theme = "mocha"
ui_fps = 30
spectrum_hz = 30
mpris_poll_ms = 100
eq_bands_db = [
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
]
transparent_background = false
album_border = false
